### ISSUE TITLE
[1.12.2] I've noticed that if you add more than 2 or 3 categories, the mod doesn't load properly and just doesn't render them

### ISSUE THREAD

**Issue by vizthex123** [TehNut-Mods/LoreExpansion#11]
Title. This is pretty annoying since this mod is the foundation for the lore in my new modpack, but for whatever reason it just isn't indexing half of the entries I've written.

Any reason why?

I might have formatted them wrong, but since there's no crash report or anything listed in the log I don't think that's the case

**Comment by TehNut** [comment]
Can you provide a copy of your lore directory so I can check it over? I can't reproduce this myself.

**Comment by vizthex123** [comment]
Sorry for the late response, I always forget to check GitHub

Here you go:

[loreexpansion.zip](https://github.com/TehNut/LoreExpansion/files/5004239/loreexpansion.zip)

**Comment by TehNut** [comment]
In `P-forgebrow.json`, you have `"doctor"` which breaks the string. You need to escape the quotes around doctor like so `\"doctor\"`.

**Comment by vizthex123** [comment]
Ah ok, forgot that json doesn't like quotes inside of quotes.

Will be sure to check that.

If I do 2 ' though, would that keep the string intact? `''doctor''`

**Comment by vizthex123** [comment]
Ok, I did what you said and it works! Thanks for fixing it.
