### ISSUE TITLE
[1.12.2] Adding more than 3 pages of lore makes half of it not load.

### ISSUE THREAD

**Issue by vizthex123** [TehNut-Mods/LoreExpansion#12]
This has been a persistent issue in the mod and it's rather irksome.

I can't have more than 3 pages of lore otherwise half of them don't load into the game properly.

I've checked the .json format using [jsonlint](https://jsonlint.com/) as well as their numeric IDs and category names, everything is fine.

It just doesn't want to work.

This mod is the crux of my modpack and I really want it to work.

**Comment by TehNut** [comment]
Is this a duplicate of #11?

**Comment by vizthex123** [comment]
Ah, it is. Forgot I had already reported it; sorry. I sent the directory as you asked in #11
