### ISSUE TITLE
Crash on getting lore

### ISSUE THREAD

**Issue by WolfieWaffle** [TehNut-Mods/LoreExpansion#2]
I have some other mods present, so this might be on their end, but the crash report makes it look like its either a mod interaction or something in this mod that is causing it to crash. If I set defaultLore to true or pick up a lore page, I get this crash:

http://pastebin.com/s8HbxD0A

**Comment by TehNut** [comment]
Does this only happen with a specific Lore page? Could I see the JSON you used?

**Comment by WolfieWaffle** [comment]
http://pastebin.com/bnS4w51h

**Comment by WolfieWaffle** [comment]
I don't know if it works for other lore pages, I couldn't get it to work at all most of the time.

**Comment by TehNut** [comment]
Taking a look. Unrelated, but you should change `"audio": "NULL",` to `"audio": "",`. Any kind of string (other than empty) will cause the audio manager to attempt to play a file. In this case, it's looking for `NULL.ogg` and not finding it.

**Comment by TehNut** [comment]
I'm not able to reproduce the crash, though I did find a bug where the `autoAdd` feature wasn't checking requirements first.

Could you try with [this](http://tehnut.info/share/LoreExpansion-1.10.2-1.1.3-CUSTOM.jar) build?

**Comment by WolfieWaffle** [comment]
Yep, that fixed the crash (changing both things) but now the lore page does not appear in my lore book.

**Comment by TehNut** [comment]
Hm. Does the Lore display in Creative/JEI? Are there any relevant errors in the console?

**Comment by WolfieWaffle** [comment]
The lore displays in Creative and JEI. It doesn't seem to go into the journal when I right click it though. I'll try with no mods installed to see if it persists, and if not ill try and find what mod is causing it, maybe it's an issue on their side.

**Comment by TehNut** [comment]
Well you currently have it set to require a lore with an ID of `blah:blah`. Unless the player has that lore, they cannot learn this one.

**Comment by WolfieWaffle** [comment]
oh, derp. I copied that from the example page, and forgot about that requirement. I'll remove it and see if that works.

**Comment by TehNut** [comment]
I just pushed `1.1.4-8` which includes the fix for the crash (among other stuff). I'm going to chalk the other issue up to "user error".

**Comment by WolfieWaffle** [comment]
XD ok, sounds good
