### ISSUE TITLE
Journal Duplication on World Join

### ISSUE THREAD

**Issue by elwooha6** [TehNut-Mods/LoreExpansion#4]
Just found a strange bug where the lore book/tablet would be added to your inventory every time you load a world regardless of whether it is your first time joining or not.

minecraft version: 1.10.2
forge version: 12.18.3.2254
mod version: 1.1.4-9

I tried both in a modpack and with no other mods present and it repeats every time I join the world, also I tested multiple worlds, same result.

**Comment by TehNut** [comment]
Welp.

I accidentally deleted a bit of the set tag name for 1.10, and 1.11 never even got the fix even though it's in the commit history.

**Comment by TehNut** [comment]
Build incoming
