### ISSUE TITLE
Audio stops upon opening journal

### ISSUE THREAD

**Issue by enarkay** [TehNut-Mods/LoreExpansion#5]
**MC version**: 1.7.10
**mod version**: 1.0.6

Closing the journal while the audio is playing works just fine and the audio continues to play. However, when I open the journal back up the audio stops playing. I've tested and confirmed this problem does not exist in the **1.0.5b version** of the mod. 

Since you're moving on to the more recent versions of minecraft, I understand that there may be little motive for you to maintain or update the mod for mc version 1.7.10. However, since this isn't a request for a new feature to be implemented but a fix for something that was working fine in the previous version and is now broken, would you be so kind and professional enough to fix the problem and save a modpack creator's day?

Your mod is so great and fantastic that it's one of my biggest shame that I've discovered this mod now, and while I surely intend to use this for more recent versions of minecraft, I would really love to include this mod in a light starting tutorial type modpack I am creating for mc version 1.7.10.

Thank you very much for your time.

**Comment by TehNut** [comment]
Sorry I do not support 1.7.10.

**Comment by CyanideX** [comment]
> would you be so kind **_and professional enough_**

Well that passive-aggressive comment is incredibly rude. Implying that someone isn't professional if they refuse to work on a dead version of Minecraft will get you nowhere.

**Comment by enarkay** [comment]
I have several things to point out, such as that despite the big number of players who are actively playing 1.7.10 I unfortunately do recognize and understand that 1.7.10 is considered a 'dead' version of minecraft for many modders, hence I either don't expect updates for 1.7.10 in the first place or even if I do then I do so with minimum hopes, and in this case I was asking for a bug fix for a problem that didn't exist in the previous version, not an implementation of a new feature. And in that aspect, I will frankly say that I still think it fits under the category of professionalism.
But I also completely admit that my expressions were aggressive and rude - I'm not here to receive a service or a product I paid for nor do I have any rights to demand something. Even though my intentions were to make a polite request with minimum hopes, I see that my thirsty hopes got in the way and turned my post into something past a polite request. I am in no place to judge the difficulty of such a bug fix, and regardless of my perception of what professionalism is that should never have been a part of my post.

Just as much as I understand your lack of motives to release any more updates for 1.7.10 including a bug fix, I would deeply like to apologize for my rudeness. You've made a point that I may not have though of myself and am quite ashamed for it, so thank you and this will not happen again. Like I already said, Lore Expansion is such a great mod that I will be enjoying very much regardless of its mc version, and I sincerely thank all of your time and efforts invested in making, maintaining, and updating the mod. Hope you all have a nice day:)

**Comment by CyanideX** [comment]
I appreciate you taking the time to express your thoughts on the matter and I personally don't see the harm in making the request for a simple big fix; however, what I think you missed was the fact that TehNut is simply the maintainer of LE and only took over the 1.10 versions which he wrote himself. For versions prior to that you should be contacting the original author, dmillerw. It's a simple mistake and is completely understandable as it isn't started clearly.

**Comment by enarkay** [comment]
Ah! Alright now that makes even a lot more sense:) I see what my mistake was, thanks for clearing that up!
