### ISSUE TITLE
Unable to Create Lore

### ISSUE THREAD

**Issue by alittlewarlord** [TehNut-Mods/LoreExpansion#6]
Hello,

I am trying to set up the Lore Expansion mod to work in a Modpack I am making. Only problem, whenever I try to give the lore to my testing player, it says that the category I have put in is not a valid lore category.
 
The code is as following:
 
{
"key": {
"id": "wake",
"category": "overworld"
},
"content": {
"title": "Wake",
"body":"Blah blah blah.",
"audio": "",
"autoplay": false
},
"sortingIndex": 1,
"autoAdd": false,
"defaultLore": true
}
 
 
 
-------------------------------
 
 
 
When I try to tell it to /lore give overworld wake, all it does is tell me that "overworld" is not a valid Lore category. This has happened with every category I have tried, including "en_US", "lore1", and "begin". 

When I try to find it in the Creative Tab, it doesn't show up. It doesn't show up in NEI or anywhere else, either.

I am using Lore Expansion 1.0.6.

I also had this problem when copy and pasting the tutorial code here on GitHub into the json file.

Have I done something wrong?
 
Thank you for your time!

**Comment by TehNut** [comment]
I do not support nor maintain the 1.7.10 version.

**Comment by teagan75** [comment]
Since you still use the same Curse site as the previous author and still offer 1.7.10 versions, wouldn't it be helpful to post a link to the old documentation? https://github.com/dmillerw/LoreExpansion_old/wiki/JSON-Documentation

**Comment by TehNut** [comment]
I don't particularly care about being helpful when it comes to 1.7.

**Comment by teagan75** [comment]
And you are part of the reason why devs have a bad name and why as a modpack developer I wouldn't support you. Dev snobbery at its best

**Comment by Growlith1223** [comment]
There's very little reason to support an old and, in my opinion, deprecated version of minecraft. Just means more work for the developers that could be spent on working on the current version.

**Comment by alittlewarlord** [comment]
Hey, yeah, I totally get not supporting it man. I figured it out on my own, Teagan75 you can drop it. It’s fine, working with old versions is bullcrap and you should probably appreciate what growlith1223 has done already. There’s no need to pester them more.

**Comment by Growlith1223** [comment]
lol it's not me that should be getting the appreciation, this isn't my mod

**Comment by alittlewarlord** [comment]
Oh oops

**Comment by alittlewarlord** [comment]
CRAP I meant TehNut sorry I just looked at the argument

**Comment by teagan75** [comment]
The comment he gave was rude. I wasn’t asking for support or fixes. Just one link on the damn Curse page because it’s helpful and nice. The dev’s comment sums up what is wrong with the MC community. There are plenty of other helpful mod devs out there worthy of my support. 

And because I was having the same issue, I decided to provide the link that was so beneath him to post, so others coming here for help will at least get a damn answer. Newer versions of MC aren’t that much better than 1.7 and a lot of mods are still in beta. Like I said, I am a Modpack developer who would like more friendly support from mod devs. But maybe that’s too much to ask.

**Comment by alittlewarlord** [comment]
I mean, he literally doesn't owe us anything cause he's another actual human being who has actual human being things to do that don't involve this at all times of day. If you could find something, and I could find something, it kinda doesn't matter that much? I'm sure other people can find it. And he has a right to be a little short if he doesn't support the version anymore.

Please, can we stop bothering him on this thread? He did nothing wrong, it's his work and we don't have any right to pester him about it.

**Comment by alittlewarlord** [comment]
And, you could probably just, comment the link so people can find it?

**Comment by TehNut** [comment]
@alittlewarlord I fucking love you man. One of the few who gets it. ♥️
